# specify the node base image with your desired version node:<version>
FROM node:10
# replace this with your application's default port
EXPOSE 3000

WORKDIR /payword-frontend

COPY . .

RUN yarn install

CMD yarn start