# This file is for development purposes only !
version: "3"

services:
  mongo:
    image: mongo

  api:
    image: registry.gitlab.com/bencoder01/payword-backend:latest
    restart: always
    depends_on:
      - mongo
    ports:
      - 3333:3333
    environment:
      - APP_ENV=production